### PR TITLE
Add Choice Korean Empire for user

### PR DESCRIPTION
**Pull request by yhpdoit**

### CODE REVIEW

**Comment by DevilIris** [comment]
Why you dont change the name of the event ww1_germany.22.a to ww1_korea or japan. 22a

**Comment by yhpdoit** [comment]
ww1_germany.22.a means "Accept offer" ww1_germany.22.b means "Deciline offer". only this mean. i use this to aviod translation problem.

i think,  accept offer should become common translaation. we don't need make japan accept offer/germany accept offer/china accept offer or other country. if anyone think good word for it, change in the future.

**Comment by Wolferos** [comment]
I agree with @DevilIris, even if it's redundant, it's better to create a ww1_japan.22.a variable because if we need to write a more personal text in the future for ww1_germany.22.a, we won't need to search for all the events using this same variable.

About the choices of the event now, how about "Ratify the Annexation Treaty", "Approve the Annexation Treaty", "We have no other choice" and "Fight for our Independency", "Enough! We Must Free Ourselves!"

**Comment by yhpdoit** [comment]
ok.ok. i understand. add translation file soon.

**Pull request closed without merging**
