### PR TITLE
Emergency fix for crashes when load save

### PR DESCRIPTION
**Pull request by MasterWaifuman**
Commented state category and manpower for 771 state because it breaks saves

### CODE REVIEW

**Review by DevilIris — APPROVED** [review]
This needs to be Updated to the new develop. I tested and it fix the main problem of Game save crashing.

**Comment by MasterWaifuman** [comment]
@DevilIris, people on steam are insane about crashes so can you tell them that i fixed it and it will come with a new update soon ( i can't comment on steam ( dunno why ) ). Meanwhile, we will wait for Wolferos.

**Comment by DevilIris** [comment]
Oh ok. If wolferos doesnt appear today im going to release a hot fix in other mod.

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
@DevilIris, that thing you did to limit AI training divisions, can you limit concretely Belgium to like 25 divisions or so, because 150 divisions for Belgium is way too much.

**Comment by Wolferos** [comment]
Hey,

Thnaks for the quick fix.
Also, I removed impassable areas due to lags every 24 hours.
About the 771 state, we should put all the victory points in the State  #1 to avoid future problem like that. I'll run some tests.

**Pull request merged**
