### PR TITLE
African/Levantine and etc. States Update

### PR DESCRIPTION
**Pull request by ComradeR**
- Map of Tripolitania was changed (number of states has not been changed, only new map of region, for now. Borders from Victoria 2, and I plan to add several states, to make it more historical.)
- Map of German Guinea was changed!
- Impassable desert! (Tested, and I didn't notice errors)
- North/West African countries have neutrality ideology
- protectorate Tunis under french control (can be released)
- New colors for African and of Levantine state colors
- Transferred one province in Poznan
- Transferred one province in Edirne
- Transferred one province in North Korea
- Transferred one province in German Namibia
- Arunachal Pradesh is Chinese in 1910 (before Simla Convention)
- Anarchist ideology fix. Anarchism now is not random for neutral countries.
- Historical flags for Tibet, Siam and etc

Screenshots show the states that have changed. Color of Egypt is not red! This is just a cosmetic tag test

### CODE REVIEW

**Comment by Wolferos** [comment]
Nice work ComradeR, a lot of very good ideas, the problem is that as soon as we edit the Map we've to do hundreds of tests to check that it does not cause crashes (throughout many full games) and all that heavy work would be in danger of being swept away with a future Paradox update.

It's for this reason that we prefer to wait for the release of Barbarossa (and the one or two hotfix updates which will certainly follow it as usual...) before implementing any major changes to the Mod Map in order to not end up with a totally crashed Mod which would be a plague to debug.

Keeping Debug's dog at a modest size has always been a daunting task, but that's what got the Mod through Together for Victory, Waking the Tiger, Man The Guns, and The Resistance updates.

Then there are a lot of things in your PR that wouldn't make any problem, do you mind if we put some of the stuff you propose on standby until all the Barbarossa related mess is behind us?

**Comment by ComradeR** [comment]
Yes, I assumed that changing of map would be more painful than cosmetic files, and therefore, I separated part of PR with states into a separate commit, and other part that can be added immediately (gfx files) to another part of PR. And please, its advisable not to postpone files "history/countries". These files correct errors in ideology, that may appear if France or Germany release African countries as independent. And I would like you not postpone files with colors of African/Levantine countries.

**Comment by Wolferos** [comment]
As Hearts of Iron IV 1.10.5 has been released we had to release a new update for the Mod so the only stuff integrated from this PR are your flags, we'll take a deeper look in the future for what we didn't integrate in the Open Beta 0.14 😉

**Comment by Wolferos** [comment]
African countries and colors have been integrated, thank you.
There is a small duplicate in `colors.txt` for NGR.

`NGR = {`
`	color = rgb { 193 124 60 }`
`	color_ui = rgb { 193 124 60 }`
`}`
`NGR = {`
`	color = rgb { 87 138 168 }`
`	color_ui = rgb { 87 138 168 }`
`}`

**Comment by Wolferos** [comment]
The Impassable Area have been updated in commit 06aac87b8889d77a2c8e393c387ea764e0e2b3b7 based on your files 😉

**Pull request closed without merging**
