### PR TITLE
Major Update

### PR DESCRIPTION
**Pull request by DevilIris**
The following countries received their infantry equipment:## UNIQUE

All european nations (1910 Scenario)
Brazil
Argentine
USA
Mexico
Australia
Canada
Japan
China and Qing
Ottoman Empire
Iran
Raj
Siam
New Zealand
Ethiopia
Afghanistan

---
Korea Annexation treaty rework and tested-ñ Now the player can choose Korea and play with them
-------
Soviet Union has his own Focus Tree and rework on the united baltic duchy when germany win the war against russia
----
Fixed the Xinhai Revolution 
Fix for the Mexican Focus tree 
Added more generals to the Ottomans 
Added more Resources 
Fixed the borders errors in South America
Added a buff for the CP. Now they have more posibilites to breakthrough to france 
 The AI now only spawn 261 units Max so this cause less lag and dont spawn units like crazy 
You have 50 Building Slots 
Add all the important cities of that age 
Added more States 
Now the neutrality idelogy can send volunteers  with 10% Tension if the AI is unhistorical germans can send volunteers to qing and bulgaria
Rework and fix some events 
Now the Soviet union end the eternal war with the entente
Fixed some OOBS 
Rework some portraits in korea 
You can convert light tank (only with the death or dishonor dlc)
Added Holland to the Bookmarks (That need a description)
Added Icons for the update of the game
Rework the Zimmerman Telegram.
-----------------------------------------------
The people who help in this part of the request are:

@MasterWaifuman // Making the sov focus tree and fixing a lot of things
@skullbe // Creating a better Korea
Kuebelwagen // For the VP
Stluvik// For the Unique Weapons of this version & Add more generals
M3Henry// For the Tank Conversions with Dlc
fedcba//Improving the equipment and focuses
MrBlazzar//For the 50 Factories
Citofis//For making more states and helping us fixing more stuff

### CODE REVIEW

**Comment by MasterWaifuman** [comment]
> Now the neutrality idelogy can send volunteers with 15% Tension 

I changed it to 10%, remember?

**Comment by DevilIris** [comment]
Ya I change that now

**Comment by MasterWaifuman** [comment]
And i added NS for benilux and russia to make them weaker through schliefen plan

**Comment by DevilIris** [comment]
Also we need to hurry finishing the goals or at least the most of goals  before the new update comes out.

**Comment by DevilIris** [comment]
i am merging the last focus trees on this Friday. I cant finish the qing focus for this update :(

**Comment by MasterWaifuman** [comment]
I spent whole day making sov focus tree (literally ( it was loooong day )) and think i cant complete before update

**Comment by DevilIris** [comment]
Well i think that we have 2 weeks more before the update comes out.

DevilIris

**Comment by MasterWaifuman** [comment]
so i think belgium focus tree i maybe can complete. (maybe)

**Comment by DevilIris** [comment]
Nice i hope that belgium get some love

DevilIris

**Comment by Wolferos** [comment]
Hello guys !

Very nice work. I've tested it, all worked fine !

I've fixed some errors in this commit https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/commit/74a265adfd677a2df1c3a08ce2b9009a2123db6a

The new region 771 is not a real region right ? It's just a "fake region" to overwrite victory points with new values?
It creates some erros in the log but doesn't seem to impact the game.
Is that correct?

I've also commented a GER strategy because the commands were unknown (https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/commit/8a2e95b84b14d01bcc8f67fb34e3ca2e6a8fa04a). I wasn't able to find those commands in HOI4 or on the Doc.

Edit: It seems also that AUH's troops are not moving avec the capitulation of RUS.

**Comment by DevilIris** [comment]
Yes the 771 state is basically all the Victory points. I know that is caising error in the log file. But in the game it doesnt matter. I think that is better have more VP.

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DevilIris** [comment]
Also we need to rework the Xinhai Revolution and set a cosmetic tag for CHI and not QIN. 

Tomorrow i will be pull request more things. 

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Wolferos** [comment]
I've tested putting all the new victory points in the last state and it works also but i understand that it's better to put it in a fake state for clarity.

In my game tests, Russia is easily beatten by GER and AUH, maybe the boost was a little too much. What do you think?
I'll have a look at the Brest Liovsk Treaty.

Paradox will release the 1.4.2 Patch in a few days, if not today.

**Comment by DevilIris** [comment]
Well we can nerf the boost but germany and AUH do suicide naval invasion.  We can add more national unity to the russian empire.

Also the ideas for russia and france have a bug 
In the text.

We can add to the russian a idea to improve the defense and entrenchment so with they could hold more.

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment]
Yeah i can remove "superior enemy" NS (which makes russia and benilux more beatable) from russia or maybe just weaken it. What do you think?

**Comment by DevilIris** [comment]
I think that we need to remove russia for that focus only belgium needs that as well luxemburg

**Pull request merged**
