### PR TITLE
Update

### PR DESCRIPTION
**Pull request by MasterWaifuman**
- Fixes for the Soviet Union. Like endless Comintern influence and other mistakes in code.
- Brasilian States Overhaul
- Fixes for Korea
- German AI fix
- Frankfurt Treaty peace mechanics reworked as well as Versailles Treaty and Treaty of Brest-Litowsk.
- Fix for light tanks tech missing effect
- Adjusted Victory Points draw distance. They now appear only when you zoom camera close to the ground.
- Small correction of Cameroon border
- Belgium AI is not allowed to unite Benelux (only with historical on)
- New colony for Germany - German Cameroon
- New colony for Germany - German Togoland
- Fixed oobs of Equador
-------------------------------------------------------------------------------------------------------------
NOT FOR CHANGELOG:
- BEL AI fix ( doesn't fix actually, but doesn't break anything ( just useless (will try something else) ) )
- Balancing Western Front (in process ( maybe not for this update ( will also fix BEL unit spam (probably) ) )

### CODE REVIEW

**Comment by DevilIris** [comment]
@MasterWaifuman  Can you fix the problem with events of japan, ww1 armistice and Frankfurt treaties. I fix a lot of bugs and other things check the log also i add a lot work in the russian civil war and other things.   

Also @Wolferos  can you merge the branch when is fixed ? please

**Comment by MasterWaifuman** [comment]
Ok

**Comment by MasterWaifuman** [comment]
> Can you fix the problem with events of japan, ww1 armistice and Frankfurt treaties.

I think i can do it only after New Year because i have to work on my own mod for school work.

**Comment by Wolferos** [comment]
Already integrated, PR too old.

**Pull request closed without merging**
