### PR TITLE
GFX Updates

### PR DESCRIPTION
**Pull request by GoneToPlaidd**
**GFX Update** _(Mainly AUH)_

_(May need to rename/look over especially for designers (once I see how you like the coding I will implement any more work that way))_

**Designers:**
-------------------------------------

**Austria**:
-------------------------------------

AUH_austro_daimler
Motorized Austro-Daimler
-------------------------------------
AUH_ganz_co
Raiding Ganz Co
-------------------------------------
AUH_ganz_krupp
Regular Naval Research Ganz Krupp
-------------------------------------
AUH_lohner
Naval Aircraft Loher
-------------------------------------
AUH_österreichische_waffenfabriksgesellschaft
Infantry Equipment Osterreichische Waffenfabriksgesellschaft 
-------------------------------------

Germany:
-------------------------------------
GER_kaiserliche_wilhelmshaven
Atlantic Fleet Kaiserliche Wilhelmshaven
-------------------------------------
**Portraits:**
Austria: 
Austrian General Generic 2 PNG
Austrian General Generic 3 PNG
Austrian General Generic 4 PNG
von_Haus PNG
von_Spaun PNG

Germany:
Paul_von_Hindenburg PNG
von_Lettow-Vorbeck PNG

Turkey:
TUR_Muhtar

### CODE REVIEW

**Comment by GoneToPlaidd** [comment]
Also if liked I can do gfx for focuses, again not really good with coding or modding, just can help out with art in case if you dont want it to be messy. 

Some Focus GFX 
---------------------
PNG RTA
PNG REA
PNG EDM
PNG CKA
PNG CEA
PNG BP

**Comment by GoneToPlaidd** [comment]
New commits add focus gfx and should be fine with coding!

Austria Focus GFX
-
ww1_auh_support_emperor
ww1_auh_contest_emperor
ww1_auh_militarism
ww1_auh_end_dual_monarchy_emperor
ww1_balkans_policy
ww1_triple_alliance

Germany Focus GFX
-
ww1_ger_contest_kaiser
ww1_ger_militarism
ww1_triple_alliance

Italy Focus GFX
-
ww1_ita_libyan_claims

Ottoman Focus GFX
-
ww1_tur_abolish_constitution

Air Formations/Aviation Effort
-
ww1_ger_aviation_effort
ww1_auh_aviation_effort
ww1_tur_aviation_effort
ww1_bul_aviation_effort
ww1_eng_aviation_effort
ww1_usa_aviation_effort
ww1_fra_aviation_effort
ww1_rus_aviation_effort
ww1_ita_aviation_effort
ww1_jap_aviation_effort
ww1_ser_aviation_effort

**Comment by GoneToPlaidd** [comment]
If implemented, I did more research and reworked the Designer GFX and so I'll just replace the DDS files whenever that is.

Reworked GFX
-
lohner_werke
ganz_krupp
ganz_danubius
austro_daimler

**Review by Wolferos — APPROVED** [review]
Thank you for this quality work, we will integrate all this into the Mod 😉

**Pull request merged**
