### PR TITLE
Major Update #1

### PR DESCRIPTION
**Pull request by DevilIris**
# This is the part 1 of my update the following files add 
Korea Annexatrion Treaty now you can play with korea & Rework of oobs ********* ## Not Tested
---------------
The following countries received their infantry equipment:##  UNIQUE
- All european nations (1910 Scenario)
- Brazil
- Argentine
- USA
- Mexico
- Australia
- Canada
- Japan
- China and Qing
- Ottoman Empire
- Iran
- Raj
- Siam
- New Zealand
- Ethiopia
- Afghanistan
--------

Now the AI dont spawn too many units only upgrade their actual units (Max = 260)
--------------------
You have 50 building slots 
----------------
You can convert the tanks (only with dlc )
----------------------
Now the Ottomans have more generals 
--------------
Add all the important cities of that age.
---------------
Fixed again the paztaza region border error of ecuador and peru 
----------------
The next update i will merge the curse of Huitzilopotchli mod as a post war focus of mexico as well with the vanilla focus of japan. 

Working on Qing focus due to the massive work and effort of the events and focus is complicated.

### CODE REVIEW

**Comment by MasterWaifuman** [comment]
AI fix is good. I remember how i always stuck in Russia because they trained over 300 units that was too overpowered Russia.

**Comment by MasterWaifuman** [comment]
You should check Japan-Korea Treaty. You made mistake in code.
image

**Comment by MasterWaifuman** [comment]
i think here
japan bug fix

**Comment by MasterWaifuman** [comment]
it was closing one for JAP section i think

**Comment by MasterWaifuman** [comment]
And another thing. Encoding of your event localisation file is wrong. it should UTF-8-BOM.

**Comment by MasterWaifuman** [comment]
I checked some of localisation files and they have wrong encoding. You should check them and set UTF-8-BOM encoding

**Comment by MasterWaifuman** [comment]
And one more thing. Japan-korea annexation treaty event ( ww1_japan.90 ) doesn't even exists.

**Comment by MasterWaifuman** [comment]
Aaaaand the t letter is redundant
japan bug fix

**Comment by DevilIris** [comment]
Yea i didnt test the event i only code it. If you find the error Can you
fix it?

DevilIris

**Comment by MasterWaifuman** [comment]
Iiii think i can't? Because i didn't merged your files into my repository i only downloaded version from your repository. I mean i can modify my files on computer, but to modify in repository i will need to merge your files into mine and bla bla bla. Here is the problem. If i do this, it will affect pull request in Wolferos repository and there would be two identical pull requests. I think that is not actually rational.

**Comment by DevilIris** [comment]
You can pull request like the laat one

DevilIris

**Comment by MasterWaifuman** [comment]
but it still need merge from your repository

**Comment by DevilIris** [comment]
Let me do apull quest to yours

DevilIris

**Comment by MasterWaifuman** [comment]
ok... i guess

**Comment by MasterWaifuman** [comment]
but like i said, it will affect pull request in Wolferos repository and there would be two identical pull requests

**Comment by DevilIris** [comment]
yea is true. Then we will work on your repository

**Comment by MasterWaifuman** [comment]
Hm... Seems that i accidently already merged your repository into mine. So i think i can fix it.

**Comment by MasterWaifuman** [comment]
I think i have more logical idea. I will test it and if it works i will change it here

**Comment by MasterWaifuman** [comment]
Nah it not works. So 10% i guess.

**Comment by DevilIris** [comment]
Oh ok its better 10 %

DevilIris

On Aug 15, 2017 3:51 AM, "Master Waifuman" <notifications@github.com> wrote:

Nah it not works. So 10% i guess.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Wolferos/Hearts-of-Iron-IV-The-Great-War/pull/133#issuecomment-322415459>,
or mute the thread

**Comment by MasterWaifuman** [comment]
i will add ai strategy which makes ger not to send troops to qin or bul

**Comment by MasterWaifuman** [comment]
and it should be tested

**Comment by DevilIris** [comment]
master waifu man the new update is here so we need to finish this parts

**Pull request closed without merging**
